# Generated by Django 5.1.5 on 2025-03-05 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_alter_category_icon_class_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='libraryapp.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_class',
            field=models.CharField(default=1, help_text='FontAwesome icon class', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
