# Generated by Django 5.1.5 on 2025-03-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_book_category_alter_category_icon_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='books', to='libraryapp.category'),
        ),
    ]
