# Generated by Django 5.1.5 on 2025-03-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0005_booklibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='related_books',
            field=models.ManyToManyField(blank=True, to='libraryapp.book'),
        ),
    ]
