# Generated by Django 5.1.5 on 2025-03-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0007_remove_booklibrary_category_booklibrary_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklibrary',
            name='categories',
        ),
        migrations.AddField(
            model_name='booklibrary',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
