# Generated by Django 5.1.5 on 2025-03-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0010_remove_booklibrary_categories_booklibrary_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklibrary',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
