# Generated by Django 5.1.5 on 2025-03-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0017_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
