# Generated by Django 5.1.5 on 2025-03-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0025_message_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
