# Generated by Django 5.1.5 on 2025-03-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0026_alter_message_options_remove_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklibrary',
            name='info_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
