# Generated by Django 5.1.5 on 2025-04-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0035_alter_passwordresetcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='preview_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
