# Generated by Django 5.1.5 on 2025-04-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0036_book_preview_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color code (e.g., #FF4500)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='translated_name',
            field=models.CharField(blank=True, help_text='Türkçe kategori adı', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_class',
            field=models.CharField(blank=True, help_text='FontAwesome icon class', max_length=100, null=True),
        ),
    ]
