# Generated by Django 5.1.5 on 2025-04-11 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0037_category_color_category_translated_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Kitap', 'verbose_name_plural': 'Kitaplar'},
        ),
        migrations.AlterModelOptions(
            name='bookcomment',
            options={'verbose_name': 'Kitap Yorumu', 'verbose_name_plural': 'Kitap Yorumları'},
        ),
        migrations.AlterModelOptions(
            name='booklibrary',
            options={'verbose_name': 'Kitaplık', 'verbose_name_plural': 'Kitaplıklar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'Şikayet', 'verbose_name_plural': 'Şikayetler'},
        ),
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'verbose_name': 'Arkadaşlık İsteği', 'verbose_name_plural': 'Arkadaşlık İstekleri'},
        ),
        migrations.AlterModelOptions(
            name='friendship',
            options={'verbose_name': 'Arkadaşlık', 'verbose_name_plural': 'Arkadaşlıklar'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mesaj', 'verbose_name_plural': 'Mesajlar'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Bildirim', 'verbose_name_plural': 'Bildirimler'},
        ),
        migrations.AlterModelOptions(
            name='passwordresetcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Şifre Sıfırlama Kodu', 'verbose_name_plural': 'Şifre Sıfırlama Kodları'},
        ),
        migrations.AlterModelOptions(
            name='recommendedbook',
            options={'verbose_name': 'Önerilen Kitap', 'verbose_name_plural': 'Önerilen Kitaplar'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'İnceleme', 'verbose_name_plural': 'İncelemeler'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Kullanıcı Profili', 'verbose_name_plural': 'Kullanıcı Profilleri'},
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='books', to='libraryapp.category', verbose_name='Kategoriler'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, null=True, verbose_name='Kapak URL'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='book',
            name='google_books_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Google Kitap ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='info_link',
            field=models.URLField(blank=True, null=True, verbose_name='Bilgi Linki'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sayfa Sayısı'),
        ),
        migrations.AlterField(
            model_name='book',
            name='preview_link',
            field=models.URLField(blank=True, null=True, verbose_name='Önizleme Linki'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Yayın Tarihi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yayıncı'),
        ),
        migrations.AlterField(
            model_name='book',
            name='related_books',
            field=models.ManyToManyField(blank=True, to='libraryapp.book', verbose_name='İlgili Kitaplar'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='libraryapp.booklibrary', verbose_name='Kitap'),
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='content',
            field=models.TextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='booklibrary',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yazar'),
        ),
        migrations.AlterField(
            model_name='booklibrary',
            name='book_id',
            field=models.CharField(max_length=150, verbose_name='Kitap ID'),
        ),
        migrations.AlterField(
            model_name='booklibrary',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='booklibrary',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Resim URL'),
        ),
        migrations.AlterField(
            model_name='booklibrary',
            name='info_link',
            field=models.URLField(blank=True, null=True, verbose_name='Bilgi Linki'),
        ),
        migrations.AlterField(
            model_name='booklibrary',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Puan'),
        ),
        migrations.AlterField(
            model_name='booklibrary',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='booklibrary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, help_text='Hex renk kodu (örneğin, #FF4500)', max_length=7, null=True, verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_class',
            field=models.CharField(blank=True, help_text='FontAwesome icon class', max_length=100, null=True, verbose_name='İkon Sınıfı'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='İngilizce İsim'),
        ),
        migrations.AlterField(
            model_name='category',
            name='translated_name',
            field=models.CharField(blank=True, help_text='Türkçe kategori adı', max_length=100, null=True, verbose_name='Türkçe İsim'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='Çözüldü mü'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi')], default='pending', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships1', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı 1'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships2', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı 2'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Okundu mu'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Okundu mu'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=255, verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Son Kullanma Tarihi'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Kullanıldı mı'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_codes', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='recommendedbook',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Yazar'),
        ),
        migrations.AlterField(
            model_name='recommendedbook',
            name='image',
            field=models.URLField(verbose_name='Resim URL'),
        ),
        migrations.AlterField(
            model_name='recommendedbook',
            name='info_link',
            field=models.URLField(verbose_name='Bilgi Linki'),
        ),
        migrations.AlterField(
            model_name='recommendedbook',
            name='published_date',
            field=models.DateField(blank=True, null=True, verbose_name='Yayın Tarihi'),
        ),
        migrations.AlterField(
            model_name='recommendedbook',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Puan'),
        ),
        migrations.AlterField(
            model_name='recommendedbook',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gönderen'),
        ),
        migrations.AlterField(
            model_name='recommendedbook',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='recommendedbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_books', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='libraryapp.book', verbose_name='Kitap'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Puan'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biyografi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Giriş'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profil Resmi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
