# Generated by Django 5.1.5 on 2025-04-15 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0038_alter_book_options_alter_bookcomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklibrary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 15, 9, 22, 52, 1785, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
