# Generated by Django 5.1.5 on 2025-04-16 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0040_alter_booklibrary_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklibrary',
            name='created_at',
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
