# Generated by Django 5.1.5 on 2025-04-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0041_remove_booklibrary_created_at_book_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='google_books_id',
            field=models.CharField(max_length=200, unique=True, verbose_name='Google Kitap ID'),
        ),
    ]
