# Generated by Django 5.1.5 on 2025-04-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0042_alter_book_google_books_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='google_books_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Google Kitap ID'),
        ),
    ]
