# Generated by Django 5.1.5 on 2025-04-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0045_alter_book_cover_url_alter_book_google_books_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklibrary',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='booklibrary',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Resim URL'),
        ),
        migrations.AlterField(
            model_name='booklibrary',
            name='info_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Bilgi Linki'),
        ),
    ]
