# Generated by Django 5.1.5 on 2025-05-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0046_alter_booklibrary_category_alter_booklibrary_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedbook',
            name='author',
            field=models.CharField(max_length=500, verbose_name='Yazar'),
        ),
        migrations.AlterField(
            model_name='recommendedbook',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Resim URL'),
        ),
        migrations.AlterField(
            model_name='recommendedbook',
            name='info_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Bilgi Linki'),
        ),
        migrations.AlterField(
            model_name='recommendedbook',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Başlık'),
        ),
    ]
